#!/bin/bash

cd ~
git clone https://github.com/AllenInstitute/neuroanalysis
cd neuroanalysis
python setup.py develop

cd ~
git clone https://github.com/AllenInstitute/aisynphys --branch=current-release --recursive
cd aisynphys
python setup.py develop

# download and cache DB file
python util/database.py --db-version=synphys_r2.0-pre3_small.sqlite
